services:
  db :
    image: postgres:16.1
    container_name: db-microservices
    restart: always
    volumes:
      - ./sql/BaseDatos.sql:/docker-entrypoint-initdb.d/BaseDatos.sql
      - ./sql/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      POSTGRES_DB: 'microservices-assessment'
      POSTGRES_USER: 'devMCN'
      POSTGRES_PASSWORD: 'm!srv2025@'
    ports:
      - '5433:5432'

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: devMCN
      RABBITMQ_DEFAULT_PASS: m!srv2025@