server:
  port: 3002

spring:
  application:
    name: msvc-accounts
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/microservices-assessment
    username: devMCN
    password: m!srv2025@
  rabbitmq:
    host: localhost
    port: 5672
    username: devMCN
    password: m!srv2025@
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
